backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "banner"
    label: "Banner"
    folder: "src/banner"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["banner"] }
      - { label: "Content", name: "content", widget: "string" }

  - name: "about"
    label: "About"
    folder: "src/about"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["about"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Small Content", name: "small_content", widget: "string" }
      - { label: "More Content", name: "more_content", widget: "string" }

  - name: "works"
    label: "Works"
    folder: "src/works"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Work-1 Title", name: "work1_title", widget: "string" }
      - { label: "Work-1 Featured Image", name: "work1_image", widget: "image" }
      - { label: "Work-1 Description", name: "work1_description", widget: "string" }
      - { label: "Work-2 Title", name: "work2_title", widget: "string" }
      - { label: "Work-2 Featured Image", name: "work2_image", widget: "image" }
      - { label: "Work-2 Description", name: "work2_description", widget: "string" }
      - { label: "Work-3 Title", name: "work3_title", widget: "string" }
      - { label: "Work-3 Featured Image", name: "work3_image", widget: "image" }
      - { label: "Work-3 Description", name: "work3_description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["works"] }

  - name: "portfolio-section-1"
    label: "Portfolio-Content-Section-1"
    folder: "src/portfolio-section-1"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["portfolio_section_1"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "portfolio-image-section-1"
    label: "Portfolio-Image-Section-1"
    folder: "src/portfolio-image-section-1"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title",widget: "list", default: ["Portfolio-Image"] }
      - { label: "Tags", name: "tags", widget: "list", default: ["portfolio_image_1"] }
      - { label: "Featured Image", name: "image", widget: "image" }

  - name: "portfolio-content-section-2"
    label: "Portfolio-Content-Section-2"
    folder: "src/portfolio-content-section-2"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["portfolio_content_section_2"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "portfolio-title-and-image-section-2"
    label: "Portfolio-Title-And-Image-Section-2"
    folder: "src/portfolio-title-and-image-section-2"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subtitle", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["portfolio_title_and_image"] }
      - { label: "Featured Image", name: "image", widget: "image" }

  - name: "gallery"
    label: "Gallery"
    folder: "src/gallery"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["gallery"] }
      - { label: "Featured Image -1 |200x267|", name: "image_1", widget: "image" }
      - { label: "Featured Image -2 |300x300|", name: "image_2", widget: "image" }
      - { label: "Featured Image -3 |200x280|", name: "image_3", widget: "image" }

  - name: "frame-content"
    label: "Frame-And-Content"
    folder: "src/frame-content"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subtitle", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["frame_content"] }
      - { label: "Content", name: "content", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }

  - name: "youtube-popup-content"
    label: "Youtube-PopUp-And-content"
    folder: "src/youtube-popup-content"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["youtube_popup_content"] }
      - { label: "Content", name: "content", widget: "string" }
      - { label: "YouTube Embed Link", name: "youtube_embed_link", widget: "string"}
      - { label: "Background", name: "background", widget: "image" }
